Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SethBlog.Data;
using SethBlog.Models;
using SethBlog.Services;

namespace SethBlog.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFileService _fileService;
        private readonly IConfiguration _configuration;

        public BlogsController(ApplicationDbContext context, IFileService fileService, IConfiguration configuration)
        {
            _context = context;
            _fileService = fileService;
            _configuration = configuration;
        }

        // GET: Blogs
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Blog.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blogs/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Blog blog, IFormFile customFile)
        {
            if (ModelState.IsValid)
            {
                blog.Created = DateTime.Now;
                blog.LatestPostDate = blog.Created; //A default of blog.Created will prevent it having to be null.
                blog.BlogImage = (await _fileService.EncodeFileAsync(customFile)) ?? await _fileService.EncodeFileAsync(_configuration["DefaultBlogImage"]);
                blog.ContentType = customFile is null ? _configuration["DefaultUserImage"].Split('.')[1] : _fileService.RecordContentType(customFile);
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Home");

            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Created")] Blog blog, IFormFile NewImage)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    blog.Updated = DateTime.Now;
                    if (NewImage is not null)
                    {
                        blog.BlogImage = await _fileService.EncodeFileAsync(NewImage);
                        blog.ContentType = _fileService.RecordContentType(NewImage);
                    }
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), "Home");
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blog.FindAsync(id);
            _context.Blog.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blog.Any(e => e.Id == id);
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SethBlog.Data;
using SethBlog.Enums;
using SethBlog.Models;
using SethBlog.Services;
using X.PagedList;

namespace SethBlog.Controllers
{
    [Authorize(Roles = "Administrator, Moderator")]
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFileService _fileService;
        private readonly IConfiguration _configuration;
        private readonly BasicSlugService _slugService;
        private readonly SearchService _searchService;
        private readonly ReadTimeService _readTimeService;

        public PostsController(ApplicationDbContext context, IFileService fileService, IConfiguration configuration, BasicSlugService slugService, SearchService searchService, ReadTimeService readTimeService)
        {
            _context = context;
            _fileService = fileService;
            _configuration = configuration;
            _slugService = slugService;
            _searchService = searchService;
            _readTimeService = readTimeService;
        }
        //GET:All Posts of one blog
        [AllowAnonymous]
        public async Task<ActionResult> BlogPostIndex(int? id, int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;
            if (id == null)
            {
                return NotFound();
            }
            ViewData["BlogName"] = _context.Blog.First(b => b.Id == id).Name;
            ViewData["BlogId"] = id;

            if (!User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                //If user is not in authorized roles, do include unpublished
                var blogPosts = await _context.Post.Where(p => p.BlogId == id && p.PostState == PostState.Published)
                    .Include(p => p.Comments)
                    .Include(p => p.Blog)
                    .OrderByDescending(p => p.PublishedDate ?? p.Created)
                    .ToPagedListAsync(pageNumber, pageSize);
                return View(blogPosts);

            }
            else
            {
                var blogPosts = await _context.Post.Where(p => p.BlogId == id)
                    .Include(p => p.Comments)
                    .OrderByDescending(p=> p.PublishedDate ?? p.Created)
                    .ToPagedListAsync(pageNumber, pageSize);

            return View(blogPosts);
            }
            
        }//GET:All Posts 
        [AllowAnonymous]
        public async Task<ActionResult> PostIndex(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;
            //if (id == null)
            //{
            //    return NotFound();
            //}
            //ViewData["BlogName"] = _context.Blog.First(b => b.Id == id).Name;
            //ViewData["BlogId"] = id;

            if (!User.IsInRole("Administrator") && !User.IsInRole("Moderator"))
            {
                //If user is not in authorized roles, do include unpublished
                var allPosts = await _context.Post.Where(p => p.PostState == PostState.Published)
                    .Include(p => p.Comments)
                    .Include(p => p.Blog) // needed to display blog title
                    .OrderByDescending(p => p.PublishedDate ?? p.Created)
                    .ToPagedListAsync(pageNumber, pageSize);
                return View(allPosts);

            }
            else
            {
                var allPosts = await _context.Post.Where(p => p.Id == p.Id) //gets ALL elements
                    .Include(p => p.Comments)
                    .Include(p => p.Blog)
                    .OrderByDescending(p => p.PublishedDate ?? p.Created)
                    .ToPagedListAsync(pageNumber, pageSize);

                return View(allPosts);
            }
            
        }
        // GET: All Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Post.Include(p => p.Blog);
            return View(await applicationDbContext.ToListAsync());
        }
        //Get: Search results
        //[HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SearchIndex(string searchString, int? page) 
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;
            ViewData["SearchString"] = searchString;
            // get results from our search service.
            var posts = await _searchService.SearchContent(searchString).ToPagedListAsync(pageNumber,pageSize);
            //posts = await posts.ToListAsync();
            return View(posts);
        }
        //GET: Tag index
        [AllowAnonymous]
        public async Task<IActionResult> TagIndex(string tagText, int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 5;
            ViewData["TagText"] = tagText;
            tagText = tagText.ToLower();
            var allPostIds = _context.Tags.Where(t => t.Text.ToLower() == tagText).Select(t => t.PostId);
            var posts = await _context.Post.Where(p => allPostIds.Contains(p.Id)).Where(p => p.PostState == Enums.PostState.Published).OrderByDescending(p => p.PublishedDate).ToPagedListAsync(pageNumber, pageSize);
            
            return View(posts);
        }

        // GET: Posts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string slug, int? fromPage)//Takes slug, not id
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }
            ViewData["FromPage"] = fromPage;

            var post = await _context.Post
                .Include(p => p.Blog)
                .Include(p => p.Comments)
                .ThenInclude(c => c.Author)//Acts on the previous include
                .Include(p => p.Tags)
                .FirstOrDefaultAsync(m => m.Slug == slug);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create(int? blogId)
        {
            var post = new Post();
            if (blogId is null)
            {
                //Syntax: (All data, One column [choosing], other column[for display])
                ViewData["BlogId"] = new SelectList(_context.Blog, "Id", "Name");

            }
            else
            {
                post.BlogId = (int)blogId;
                post.Blog = _context.Blog.Find(post.BlogId);
            }
            return View(post);
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BlogId,Title,Abstract,Content,PostState")] Post post, IFormFile customFile, List<string> TagValues)
        {
            if (ModelState.IsValid)
            {
                post.ReadTime = _readTimeService.CalcReadTime(post.Content);
                post.Created = DateTime.Now;
                post.PostImage = (await _fileService.EncodeFileAsync(customFile)) ?? await _fileService.EncodeFileAsync(_configuration["DefaultBlogImage"]);
                post.ContentType = customFile is null ? _configuration["DefaultUserImage"].Split('.')[1] : _fileService.RecordContentType(customFile);
                if (post.PostState == PostState.Published)
                {
                    post.PublishedDate = DateTime.Now;
                    var blog = _context.Blog.First(b => b.Id == post.BlogId);
                    blog.LatestPostDate = post.PublishedDate;
                }
                //Slug stuff
                var slug = _slugService.UrlFriendly(post.Title);
                if (_slugService.IsUnique(slug))
                {
                    post.Slug = slug;
                }
                else //if there is already a slug with that name: The user must change title.
                {
                    ModelState.AddModelError("Title", "Your title is not unique enough, there is another title that is similar.");
                    ModelState.AddModelError("", "Your title is not unique enough, there is another title that is similar.");
                    ViewData["TagValues"] = string.Join(",", TagValues);
                    return View(post);
                }
                var tagList = new List<Tag>();
                foreach (var tag in TagValues)
                {
                    var newTag = new Tag()
                    {
                        PostId = post.Id,
                        Text = tag
                    };
                    _context.Add(newTag);
                    tagList.Add(newTag);
                }
                post.Tags = tagList;
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("BlogPostIndex", new { id = post.BlogId });
            }
            ViewData["TagValues"] = string.Join(",", TagValues);
            ViewData["BlogId"] = new SelectList(_context.Blog, "Id", "Name", post.BlogId);
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.Include(p => p.Tags).FirstOrDefaultAsync(p=> p.Id == id);

            if (post == null)
            {
                return NotFound();
            }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - The Coder's Codex</title>
    <!-- Meta -->
    <meta property="og:title" content="@ViewData["Title"]">
    @await RenderSectionAsync("Meta", required: false)
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Seth's Blog">
    <meta name="author" content="Seth A. Burleson">
    <link rel="shortcut icon" href="~/img/favicon.ico">
    <link href="~/css/summernote-bs4.min.css" rel="stylesheet" />
    <!-- FontAwesome JS-->
    <script defer src="~/fontawesome/js/all.min.js"></script>

    <!-- Theme CSS -->
    @* animate.style sheet *@
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    
    @*<link href="~/scss/theme-7.css" rel="stylesheet" />*@
    <link href="~/css/theme-7.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body>

    <header class="header text-center">
        <h1 class="blog-name pt-lg-4 mb-0"><a asp-controller="Home" asp-action="index"><img alt="The Coder's Codex" src="~/img/smallrescoderscodex.png" class="img-fluid" /></a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/img/profile-img.jpg" alt="image">

                    <div class="bio mb-3">An arcane repository of coding tips, tutorials, and musings.  <br><a href="https://sethbcoding.com" target="_blank">Find out more about me</a></div><!--//bio-->
                    <ul class="social-list list-inline py-3 mx-auto">
                        <li class="list-inline-item"><a target="_blank" href="https://twitter.com/sbrevolution5"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a target="_blank" href="https://www.linkedin.com/in/seth-a-burleson-a1555211a/"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a target="_blank" href="https://github.com/sbrevolution5"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item"><a target="_blank" href="https://stackoverflow.com/users/14775351/sbrevolution5"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
                        <li class="list-inline-item"><a target="_blank" href="https://dev.to/sbrevolution5"><i class="fab fa-dev fa-fw"></i></a></li>
                    </ul><!--//social-list-->
                    <hr>
                </div><!--//profile-section-->

                <ul class="navbar-nav flex-column text-center w-100">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Browse Blogs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Posts" asp-action="PostIndex">All Posts</a>
                    </li>
                    <li><hr /></li>
                    @if (User.IsInRole("Administrator") || User.IsInRole("Moderator"))
                    {

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Blogs" asp-action="Index">Blogs Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Comments" asp-action="Dashboard">Moderator Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <hr />
                        </li>
                    }
                    <partial name="_LoginPartial" />
                </ul>
                <hr />

                <div class="my-2 my-md-3">
                    <a class="btn btn-primary" href="https://SethBCoding.com" target="_blank">Get in Touch</a>
                </div>
                <hr />
                <form asp-action="SearchIndex" asp-controller="Posts">
                    <div class="form-group input-group">
                        <input type="text"
                               class="form-control" name="SearchString" id="" aria-describedby="helpId" placeholder="Search...">
                        <div class="input-group-append">

                            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </nav>
    </header>
    <div class="main-wrapper">
        <div class="container">

            <main role="main" class="pb-3">

                @RenderBody()
            </main>
        </div>

        <footer class="footer text-center py-2 theme-bg-dark">
            @*<div class="row">
                <div class="col-md-11">*@

            <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">&copy; 2021 - SethBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers.  Template Edited by <a href="https://sethbcoding.com">Seth A. Burleson</a></small>
                @*</div>
                <div class="col-md-1 d-sm-none"></div>
            </div>*@

        </footer>
    </div><!--//main-wrapper-->
    <!-- Javascript -->
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/summernote-bs4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#summernote').summernote()
        });

    </script>
    <!-- Summer Note - Responsive image fix -->
    <script>
                $(document).ready(function () {
                    $("img").addClass("img-fluid");
                $("img").parent("span").css("width", "auto");
                $("img").parent("span").css("height", "auto");
            });
    

    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>